config/routes.rb
Rails.application.routes.draw do
  get 'movimentacoes/iniciar_saque'

  post 'movimentacoes/sacar'

  root 'movimentacoes#iniciar_saque'

end

app/models/saque.rb
class Saque
  attr_reader :valor, :quantidade
  
	def initialize(quantidade, valor)
		@valor = valor
		@quantidade = quantidade
	end

  def eql?(saque)
    self.valor.eql?(saque.valor) && self.quantidade.eql?(saque.quantidade)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movimentacoes_controller.rb
class MovimentacoesController < ApplicationController
  def iniciar_saque
  end

  def sacar
    caixa = CaixaService.new
    @valor_sacado = params[:valor].to_i
    @saque = caixa.retornaSaque @valor_sacado
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movimentacoes_helper.rb
module MovimentacoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DojoCaixaEletronico</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movimentacoes/iniciar_saque.html.erb
<h1>Saque [Banco XYZ]</h1>
<%= form_tag controller: :movimentacoes, action: :sacar do %>
  <%= label_tag :valor, "Valor" %>
  <%= number_field_tag(:valor, in: 2.0..1000.0, step: 1) %>
  <%= submit_tag "Sacar" %>
<% end %>

app/views/movimentacoes/sacar.html.erb
<h1>Confirmação de Saque</h1>
<p>Você sacou: <strong><%= @valor_sacado %></strong></p>
<ul>
  <% @saque.each do |cedula| %>
    <li><%= cedula.quantidade %> cédula(s) de <%= cedula.valor %> </li>
<% end %>
</ul>
<%= link_to "Novo Saque", movimentacoes_iniciar_saque_url %>